#!/bin/sh

case "$1" in
	start)
		# load dependency modules
		NRDEVICES=$(grep -c ^processor /proc/cpuinfo | sed 's/^0$/1/')
		MODPROBE_ARGS="num_devices=${NRDEVICES}"
		modprobe zram $MODPROBE_ARGS
		# Calculate memory to use for zram (1/2 of ram)
		totalmem=`LC_ALL=C free | grep -e "^Mem:" | sed -e 's/^Mem: *//' -e 's/  *.*//'`
		mem=$(((totalmem / 2 / ${NRDEVICES}) * 1024))
		# initialize the devices
		for i in $(seq ${NRDEVICES}); do
			DEVNUMBER=$((i - 1))
			echo $mem > /sys/block/zram${DEVNUMBER}/disksize
			mkswap /dev/zram${DEVNUMBER}
			swapon /dev/zram${DEVNUMBER}
		done
	;;
	stop)
		if DEVICES=$(grep zram /proc/swaps | awk '{print $1}'); then
			for i in $DEVICES; do
				swapoff $i
			done
		fi
		rmmod zram
	;;
	restart|reload)
		"$0" stop
		"$0" start
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
