#!/bin/sh
#
# Mount All Filesystems
#
source /etc/default/storage

getdevfromname()
{
	local temp_device
	temp_device=`cat /proc/mtd | grep $1`
	if [ "$temp_device" != "" ]; then
		temp_device=${temp_device%:*}
		if [ "$temp_device" != "" ]; then
			echo -n /dev/$temp_device
		fi
	fi
}

mountnand()
{
	local device
	mkdir -p ${STORAGE}
	device=`getdevfromname Filesystem | sed -e "s@mtd@mtdblock@"`
	if [ "$device" == "" ]; then
		echo "Can't find NAND Filesystem :("
	else
		echo Mount Filesystem $device
		mount -t jffs2 $device ${STORAGE} -o noatime
	fi
}

case "$1" in
  start)
	mountnand
	mkdir -p /mnt/downloads
	if [ -f ${STORAGE}/fstab ]; then
		echo "Have external fstab mounting all filesystems"
		mount -a -T ${STORAGE}/fstab
	fi
	if [ ! -f ${STORAGE}/shadow ];then
		cp /etc/shadow ${STORAGE}/shadow
	fi
	if [ -f ${STORAGE}/shadow ];then
		rm /etc/shadow
		ln -sf ${STORAGE}/shadow /etc/shadow
	fi
	if [ ! -d ${STORAGE}/root ];then
		cp -a /root ${STORAGE}/
	fi
	if [ -d ${STORAGE}/root ];then
		find /root -mindepth 1 -maxdepth 1 -exec rm -rf {} ';'
		mount ${STORAGE}/root /root -o bind
        fi
	;;
  stop)
	sync
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

