#!/bin/sh
#
# sshd        Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

umask 077

start() {
	# Start ntp date update
	ntpd -d -q -p pool.ntp.org
	# Create any missing keys
	if [ ! -d /mnt/nand/ssh ];then
		mkdir /mnt/nand/ssh
		cp /etc/ssh/* /mnt/nand/ssh
	fi
	if [ -d /mnt/nand/ssh ];then
		mount /mnt/nand/ssh /etc/ssh -o bind
	fi
	/usr/bin/ssh-keygen -A

	printf "Starting sshd: "
	/usr/sbin/sshd
	touch /var/lock/sshd
	echo "OK"
}
stop() {
	printf "Stopping sshd: "
	killall sshd
	rm -f /var/lock/sshd
	umount /etc/ssh
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
