#!/bin/sh
#
# sshd        Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

umask 077

NAND_SSH_DIR=/mnt/nand/ssh


setTimeFromInet() {
    while true ; do
        ntpd -d -q -p europe.pool.ntp.org
        if [ $? -eq 0 ]; then
            break
        else
            #Failed! Timeout 5s
            sleep 5
        fi
    done
}

start() {
	# Start ntp date update
	setTimeFromInet &
	# Create any missing keys
	if [ ! -d ${NAND_SSH_DIR} ]; then
		mkdir ${NAND_SSH_DIR}
		find /etc/ssh/ -mindepth 1 -maxdepth 1 -exec cp -a {} ${NAND_SSH_DIR} ';'
	fi
	if [ -d ${NAND_SSH_DIR} ]; then
		find /etc/ssh/ -mindepth 1 -maxdepth 1 -exec rm -rf {} ';'
		mount ${NAND_SSH_DIR} /etc/ssh --bind
	fi
	/usr/bin/ssh-keygen -A

	printf "Starting sshd: "
	/usr/sbin/sshd
	touch /var/lock/sshd
	echo "OK"
}
stop() {
	printf "Stopping sshd: "
	killall sshd
	rm -f /var/lock/sshd
	umount /etc/ssh
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
