#!/bin/sh
#
# sshd        Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

umask 077

source /etc/default/storage
SSH_STORAGE_DIR=${STORAGE}/ssh

setTimeFromInet() {
    while true ; do
        ntpd -d -q -p europe.pool.ntp.org
        if date | grep 1970 ; then
            #Failed! Timeout 5s
            sleep 5
        else
            break
        fi
    done
}

start() {
	# Start ntp date update
	setTimeFromInet > /dev/null 2>&1 &
	# Create any missing keys
	if [ ! -d ${SSH_STORAGE_DIR} ]; then
		mkdir ${SSH_STORAGE_DIR}
		find /etc/ssh/ -mindepth 1 -maxdepth 1 -exec cp -a {} ${SSH_STORAGE_DIR} ';'
	fi
	if [ -d ${SSH_STORAGE_DIR} ]; then
		find /etc/ssh/ -mindepth 1 -maxdepth 1 -exec rm -rf {} ';'
		mount ${SSH_STORAGE_DIR} /etc/ssh --bind
	fi
	/usr/bin/ssh-keygen -A

	printf "Starting sshd: "
	/usr/sbin/sshd
	touch /var/lock/sshd
	echo "OK"
}
stop() {
	printf "Stopping sshd: "
	killall sshd
	rm -f /var/lock/sshd
	umount /etc/ssh
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
