#!/bin/sh
#
# Start the wireless network....
#

source /etc/default/storage

case "$1" in
  start)
	if [ "`cat /proc/net/dev | grep wlan0`" != "" ];then
		if [ -f ${STORAGE}/wpa_supplicant.conf ];then
			printf "Starting network: "
			wpa_supplicant -i wlan0 -c ${STORAGE}/wpa_supplicant.conf -B && wpa_cli -a /usr/share/wpa/wpa_dhcp.sh -B
			[ $? = 0 ] && echo "OK" || echo "FAIL"
		else
			printf "No ${STORAGE}/wpa_supplicant.conf config found"
		fi
	 fi
	;;
  stop)
	printf "Stopping network: "
	kill -9 `pidof wpa_supplicant`
	kill -9 `pidof wpa_cli`
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
