#!/bin/sh
#
# Starts cups.
#

NAND_CUPS_DIR=/mnt/nand/cups

start() {
	printf "Starting cups: "
	umask 077

	if [ ! -d ${NAND_CUPS_DIR} ]; then
		mkdir ${NAND_CUPS_DIR}
		find /etc/cups/ -mindepth 1 -maxdepth 1 -exec cp -a {} ${NAND_CUPS_DIR} ';'
	fi
	if [ -d ${NAND_CUPS_DIR} ]; then
		chown root:lp ${NAND_CUPS_DIR}
		chmod 775 ${NAND_CUPS_DIR}
		find /etc/cups/ -mindepth 1 -maxdepth 1 -exec rm -rf {} ';'
		mount ${NAND_CUPS_DIR} /etc/cups --bind
	fi

	start-stop-daemon -S -q -p /var/run/cups.pid \
		--exec /usr/sbin/cupsd
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping cups: "
	start-stop-daemon -K -q -p /var/run/cups.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
